### PR TITLE
Link generic sensor permission revocation algorithm and fix note links

### PR DESCRIPTION
**Pull request by anssiko**
Apply this patch Bikeshed build warnings are history.

### CODE REVIEW

**Comment by anssiko** [comment]
@marcoscaceres PTAL.

**Comment by anssiko** [comment]
Thanks! The Travis build failure seems unrelated.

**Comment by anssiko** [comment]
Thanks!

Unrelated, but it seems deploy.sh was either not executed or failed, since the latest Travis CI Deploy to GitHub Pages is from Apr 19: https://github.com/w3c/permissions/commit/be85d0174eacb398bf5f27dbc53781bfc52818fa

**Comment by marcoscaceres** [comment]
yeah, I need to poke at it :(

**Comment by marcoscaceres** [comment]
@mounirlamouri, as you wrote the script, so I was wondering if maybe you can look at it? Be quicker than me trying to figure it out.

**Pull request merged**
