### PR TITLE
Simplify GC model

### LINKED ISSUE #266: Definition of PermissionStatus lifetime
According to current spec (https://w3c.github.io/permissions/#permissionstatus-gc), PermissionStatus object should be kept alive if it has event listener or a task is queued. This definition may prolong the lifetime of PermissionStatus object (once client sets change event listener, the object will never be collected). 

For example, in the case where we create a PermissionStatus with an iframe and then remove the iframe:
```
iframe.contentWindow.navigator.permissions.query({name:featureName}).then((status) => {
    status.onchange = stateChangeCallback;
    iframe.contentWindow.asyncRequestPermissionForFeature(featureName); 
    setTimeout(() => { iframe.remove(); }, someTimeout);
    status = null;
}
```
Is it necessary to keep status object alive and fire events after iframe is gone?
It seems current Chrome currently stops firing events after global object is gone.

Spec should be more specific about when it's Okay to stop firing event (and stop keeping the PermissionStatus alive). "Only when PermissionStatus has no event listener" does not sound right.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #266

The following tasks have been completed:

 * [x] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/30189)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=236349)
 * [x] Blink (link to issue)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=1754372)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/360.html" title="Last updated on Feb 9, 2022, 2:43 PM UTC (4452fbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/360/f503804...4452fbc.html" title="Last updated on Feb 9, 2022, 2:43 PM UTC (4452fbc)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Added test: https://github.com/web-platform-tests/wpt/pull/30189

Checking manually with the code below, this doesn't appear to be implemented in WebKit or Gecko. 

```JS
(async () => {
  const perm = await navigator.permissions.query({ name: "geolocation" });
  perm.onchange = console.log;
  console.log("going out of scope")
  // bye bye perm
})();
// prompts for permission
navigator.geolocation.getCurrentPosition(console.log);
```

**Comment by marcoscaceres** [comment]
Filed bugs for Gecko and WebKit...

**Comment by marcoscaceres** [comment]
I’ll see if I can patch Gecko.

**Review by miketaylr — APPROVED** [review]
LGTM

**Pull request merged**
