### PR TITLE
Editorial: fix tidy errors

### PR DESCRIPTION
**Pull request by OrKoN**
Looks like there was a missing `</div>` in https://github.com/w3c/permissions/pull/431

Also, I applied fixes produced by `HTML Tidy for Apple macOS version 5.9.20`.

***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/434.html" title="Last updated on Jan 12, 2024, 4:14 PM UTC (b6c3da9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/434/1a263f6...OrKoN:b6c3da9.html" title="Last updated on Jan 12, 2024, 4:14 PM UTC (b6c3da9)">Diff</a>

### CODE REVIEW

**Comment by OrKoN** [comment]
@miketaylr could you please take a look? There is an error related to accelerometer reference not being found but it looks unrelated to me. Do you know how to fix it?

**Comment by OrKoN** [comment]
@miketaylr I have published the fix for accelerometer definition separately in https://github.com/w3c/permissions/pull/435

**Comment by miketaylr** [comment]
> @miketaylr I have published the fix for accelerometer definition separately in #435

@OrKoN I merged that one, want to rebase?

**Review by miketaylr — APPROVED** [review]
thanks!

**Pull request merged**
