### PR TITLE
Remove 'device-info' permission

### LINKED ISSUE #161: "prompt the user to choose" algorithm impedance mismatch.
In https://github.com/w3c/mediacapture-main/issues/487 UAs should have a choice to use either the [request permission to use](https://w3c.github.io/permissions/#request-permission-to-use) algorithm or the [prompt the user to choose](https://w3c.github.io/permissions/#prompt-the-user-to-choose) algorithm, for Firefox's permission prompt.

But it takes a *paramdescriptor* and a list of related *options*, which only works if we don't use `deviceId`. That happens to work since Firefox only persists permission *per kind* today.

However, both specs put a lot of effort to optionally support permission *per deviceId* as well.

In that case, the [prompt the user to choose](https://w3c.github.io/permissions/#prompt-the-user-to-choose) algorithm would need to take a list of related *paramdescriptors*, because each descriptor has its own *deviceId*, right?

### LINKED ISSUE #203: Remove "device-info" permission
https://github.com/w3c/mediacapture-main/pull/641 removed use of the "device-info" permission.
It should be removed here as well.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #203
closes #161 

The following tasks have been completed:

 * [ ] Modified Web platform tests - change to IDL will be handled Automatically. 

Implementation commitment:

 * [X] WebKit - not implemented. 
 * [ ] Blink - doesn't seem to be implemented
 * [X] Gecko - not implementer

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 26, 2021, 10:02 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fpermissions%2Fe87340adff4e9a012095f482c0b40f7a6ea5fa11%2Findex.bs&force=1&md-warning=not%20ready)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/permissions%23253.)._
</details>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@youennf, any chance you take a look?

**Comment by marcoscaceres** [comment]
@youennf, also, any idea if anything needs to happen to https://github.com/web-platform-tests/wpt/blob/master/mediacapture-streams/MediaDevices-enumerateDevices-returned-objects.https.html ?

**Comment by youennf** [comment]
Looks good to me.
The permission request algorithm section could be further simplified since we probably do something like:
1. Let result be ...
2. Return result.

> @youennf, also, any idea if anything needs to happen to https://github.com/web-platform-tests/wpt/blob/master/mediacapture-streams/MediaDevices-enumerateDevices-returned-objects.https.html ?

I think we can keep it as is.

**Review by jan-ivar — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Thanks @youennf. Good point about the permission request also. I'll do the cleanup as a followup.

**Pull request merged**
