### PR TITLE
Introduce Browser Permissions for WebDriver BiDi

### LINKED ISSUE #424: Umbrella / Meta: Browser Permissions for WebDriver BiDi as an extension module
WebDriver BiDi spec umbrella issue: https://github.com/w3c/webdriver-bidi/issues/587

"Interacting with Permissions for Powerful Features"

The [**WebDriver BiDi spec**](https://w3c.github.io/webdriver-bidi/) should support interaction with **browser permissions** as an [extension module](https://w3c.github.io/webdriver-bidi/#extension-modules). These permissions represent a user's choice to allow or deny access to "powerful features" of the platform. For developers, the specification standardizes an API to query the permission state of a powerful feature, and be notified if a permission to use a powerful feature changes state.

The Permissions spec already supports [WebDriver classic](https://www.w3.org/TR/permissions/#set-permission-command). This bug is about making it support [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/) as well.

[For Puppeteer it would be nice to add as the next step](https://github.com/w3c/permissions/pull/425#pullrequestreview-1734377396):

# Tracking

- [ ] MPV / Initial PR: https://github.com/w3c/permissions/pull/425
- [ ] TODO: Add `user context` to `SetPermissionParameters`
- [ ] TODO: Add `origin` to `SetPermissionParameters`

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #424

The following tasks have been completed:

 * [ ] Modified Web platform tests: https://github.com/web-platform-tests/wpt/issues/43305

Implementation commitment:

 * [x] [WebKit](https://bugs.webkit.org/show_bug.cgi?id=265621)
 * [x] Blink (link to issue): https://github.com/GoogleChromeLabs/chromium-bidi/issues/1585
 * [ ] Gecko (link to issue): https://github.com/mozilla/standards-positions/issues/930

Based on https://github.com/w3c/permissions/pull/425 by @thiagowfx

***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/431.html" title="Last updated on Dec 8, 2023, 2:22 PM UTC (925957d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/431/aaff51e...OrKoN:925957d.html" title="Last updated on Dec 8, 2023, 2:22 PM UTC (925957d)">Diff</a>

### CODE REVIEW

**Comment by miketaylr** [comment]
@OrKoN I see this is currently a draft, happy to review when you think it's ready.

**Comment by OrKoN** [comment]
@miketaylr thanks! I double checked if I have included everything from the previous PR and looks like I fixed the compilation errors so I believe it's now ready for review.

**Review by miketaylr — APPROVED** [review]
LGTM, but let's get someone else to review as well (preferably someone more familiar with WebDriver-BiDi). :)

**Comment by marcoscaceres** [comment]
Filed [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=265621)... 

hey, @gsnedders, would you mind having a look at this too?

**Review by marcoscaceres — APPROVED** [review]
We reviewed on the WebKit side and we are content for this to land too.

**Comment by miketaylr** [comment]
> @miketaylr do you know if we need more reviewers? I can start working on WPT tests and Chrome implementation at the end of December. Should we wait until WPT tests are there before landing?

Nope - we're good on the review side of things, especially with WebKit's support. It would be ideal if the WPTs landed before we merged, but if you pinky swear to do them I don't mind merging now.

**Comment by OrKoN** [comment]
@miketaylr I have started WPT tests here https://github.com/web-platform-tests/wpt/pull/43802 and started to work on the implementation. One thing I have noticed is that probably we would need to adjust the BiDi part of the spec text. In particular, `Let settings be the current settings object.` is ambiguous in the context of WebDriver BiDi and we should explicitly specify which browsing context to use. Does it make sense to make those changes in this PR and land this and start a new one?

**Comment by miketaylr** [comment]
@OrKoN let's do whatever is simplest for you. I'm happy to merge this as-is, and we can iterate in a new PR, or we can continue here.

**Comment by OrKoN** [comment]
@miketaylr I think it will be simpler to land this first so it's easier to review the differences and avoid merge conflicts. Would you mind merging the PR then?

**Comment by miketaylr** [comment]
Thanks Marcos! Sorry to have missed this notification @OrKoN...

**Pull request merged**
