### PR TITLE
Run Tidy and fix ReSpec errors.

### PR DESCRIPTION
**Pull request by jyasskin**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Argh... I've lost write access too :(

**Comment by marcoscaceres** [comment]
@dontcallmedom, can you please add me as a collaborator?

**Comment by dontcallmedom** [comment]
done @marcoscaceres

**Comment by mounirlamouri** [comment]
I would like to investigate why tidy doesn't run the same way for you and me before merging this. Running tidy locally for me will revert your changes...

Though, your respec warning fixes LGTM. If you can just send a PR with that, I could merge it ASAP.

**Comment by marcoscaceres** [comment]
One of you needs to update tidy. Please check your versions.

**Comment by jyasskin** [comment]
`tidy --version` returns 'HTML Tidy for Mac OS X version 5.1.25' and 'HTML Tidy for Linux version 5.1.25', and they don't change each others' output.

**Comment by marcoscaceres** [comment]
Note we might have use HTML5 tidy. See contributor doc.

**Comment by jyasskin** [comment]
The [contributor doc](https://github.com/w3c/permissions/blob/gh-pages/contributing.md#running-html5-tidy) has no link. Googling for "HTML5 Tidy" yields https://github.com/htacg/tidy-html5, whose homepage is http://www.html-tidy.org/, and I'm using the latest version of that. Please install that on your systems.

**Comment by mounirlamouri** [comment]
I cleaned up my install and upgraded tidy and it seems that I now get the same output \o/

**Pull request merged**
