### PR TITLE
Rename 'display' permission to 'display-capture'.

### PR DESCRIPTION
**Pull request by jan-ivar**
To align with https://github.com/w3c/mediacapture-screen-share/pull/87.

***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/permissions/pull/188.html" title="Last updated on Dec 31, 2018, 8:19 PM UTC (b2054b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/188/a951a0e...jan-ivar:b2054b9.html" title="Last updated on Dec 31, 2018, 8:19 PM UTC (b2054b9)">Diff</a>

### CODE REVIEW

**Comment by jan-ivar** [comment]
@mounirlamouri, @marcoscaceres, @uysalere PTAL.

**Comment by jan-ivar** [comment]
This is still not showing up on https://w3c.github.io/permissions/#enumdef-permissionname

@marcoscaceres can you pull the crank (or show me how)?

**Comment by marcoscaceres** [comment]
@jan-ivar, sorry for the delay... I can't seem to get BikeShed to work for me locally on this computer I'm on :( All you need to do is:

1. Install bikeshed. 
1. `git checkout gh-pages`.  
1. `git merge master`
1. `bikeshed`
1. And then finally commit the regenerated HTML file into gh-pages

**Comment by marcoscaceres** [comment]
@jan-ivar gave you write access, so you can push.

**Comment by jan-ivar** [comment]
@marcoscaceres Pushed, thanks!

If it helps, I always use bikeshed remotely:
```
curl https://api.csswg.org/bikeshed/ -F file=@index.bs -F force=1 > index.html
```

**Comment by marcoscaceres** [comment]
Ah, forgot about that! thanks @jan-ivar!

**Pull request merged**
