### PR TITLE
Editorial: add example of prompt timing out

### LINKED ISSUE #430: Can 'prompt the user to choose' return deny after some implementation specific timeout?
Following on https://github.com/w3c/mediacapture-screen-share/issues/287, it may be good if the spec could add a note stating that the choose selection could return denied without a user action: implementation specific timeout, device sleep...

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #430

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/432.html" title="Last updated on Dec 1, 2023, 2:00 AM UTC (6b3f7f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/432/aaff51e...6b3f7f0.html" title="Last updated on Dec 1, 2023, 2:00 AM UTC (6b3f7f0)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Pinged the folks in https://github.com/w3c/mediacapture-screen-share/issues/287 to give them a chance to comment.

**Review by youennf — APPROVED** [review]

**Comment by eladalon1983** [comment]
I'm generally supportive (as per https://github.com/w3c/mediacapture-screen-share/issues/287). But from an almost editorial perspective, I'd mention that timing out does not appear to me an example of "exploring UI within this framework." It's Web-exposed behavior.

Maybe replace:
> User agents should be able to explore lots of UI within this framework (e.g., a permission prompt
> could time out and automatically return "denied" without the user making an explicit selection).

With:
> User agents should be able to explore lots of UI within this framework.
> Permission prompts MAY even time out and automatically return "denied"
> without the user making an explicit selection. User agents MAY employ
> heuristics to automatically return "denied" if they don't believe the permission
> fits the user's intention at the time.

**Review by miketaylr — APPROVED** [review]
LGTM

**Comment by miketaylr** [comment]
> I'm not sure that this is editorial. Timing out does not appear to me an example of "exploring UI within this framework." In part because it's Web-exposed behavior.

https://www.w3.org/TR/permissions/#prompt-the-user-to-choose step 4 covers the normative bits. You could probably argue that a timeout isn't "UI", but you could also argue it's "UX". 🤷 Seems fine to me. :)

**Pull request merged**
